"""humidity may be absent

A device that reports no humidity used to have one invented for it as 0.0 %,
which is physically implausible in a refrigerated box and plotted as a real
measurement. The column is nullable so an absent reading stays absent.

Revision ID: 0fa095944c6f
Revises: 31d1fde4f731
Create Date: 2026-09-25 10:30:28.569552

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fa095944c6f'
down_revision: Union[str, Sequence[str], None] = '31d1fde4f731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Autogenerated against PostgreSQL, where a plain ALTER COLUMN works. SQLite
# cannot alter a column in place at all, so both directions go through
# batch_alter_table, which rewrites the table there and is a no-op wrapper
# everywhere else. One migration, both backends.


def upgrade() -> None:
    """Make sensor_readings.humidity_pct nullable."""
    with op.batch_alter_table("sensor_readings") as batch:
        batch.alter_column("humidity_pct", existing_type=sa.Float(),
                           nullable=True)


def downgrade() -> None:
    """Make it required again.

    Any row whose humidity is genuinely absent has to be given a value before
    the column can be NOT NULL, so fill it with 0.0 - which is exactly the
    fabricated reading this migration exists to stop producing.
    """
    op.execute("UPDATE sensor_readings SET humidity_pct = 0.0 "
               "WHERE humidity_pct IS NULL")
    with op.batch_alter_table("sensor_readings") as batch:
        batch.alter_column("humidity_pct", existing_type=sa.Float(),
                           nullable=False)
