"""device events

Revision ID: 31d1fde4f731
Revises: 8c3bbeaab59a
Create Date: 2026-09-25 06:22:19.419179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d1fde4f731'
down_revision: Union[str, Sequence[str], None] = '8c3bbeaab59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=48), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_truck_id'), 'device_events', ['truck_id'], unique=False)
    op.create_index('ix_device_events_truck_ts', 'device_events', ['truck_id', 'ts'], unique=False)
    op.create_index(op.f('ix_device_events_ts'), 'device_events', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_events_ts'), table_name='device_events')
    op.drop_index('ix_device_events_truck_ts', table_name='device_events')
    op.drop_index(op.f('ix_device_events_truck_id'), table_name='device_events')
    op.drop_table('device_events')
    # ### end Alembic commands ###
