"""baseline schema

Revision ID: 8c3bbeaab59a
Revises: 
Create Date: 2026-09-24 20:16:43.562578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3bbeaab59a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('peak_temperature_c', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_truck_id'), 'incidents', ['truck_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('safe_min_temp_c', sa.Float(), nullable=False),
    sa.Column('safe_max_temp_c', sa.Float(), nullable=False),
    sa.Column('shelf_life_hours', sa.Float(), nullable=False),
    sa.Column('value_qar_per_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rejected_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('origin_id', sa.String(length=32), nullable=False),
    sa.Column('destination_id', sa.String(length=32), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('geometry', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=48), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('g_force', sa.Float(), nullable=False),
    sa.Column('door_open', sa.Boolean(), nullable=False),
    sa.Column('refrigeration_on', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_readings_truck_ts', 'sensor_readings', ['truck_id', 'ts'], unique=False)
    op.create_index(op.f('ix_sensor_readings_truck_id'), 'sensor_readings', ['truck_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_ts'), 'sensor_readings', ['ts'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('speed_multiplier', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plate', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('route_id', sa.String(length=32), nullable=True),
    sa.Column('destination_id', sa.String(length=32), nullable=True),
    sa.Column('batch_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('available_capacity_kg', sa.Float(), nullable=False),
    sa.Column('min_temp_c', sa.Float(), nullable=False),
    sa.Column('max_temp_c', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_batches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('production_date', sa.String(length=16), nullable=False),
    sa.Column('expiry_date', sa.String(length=16), nullable=False),
    sa.Column('safe_min_temp_c', sa.Float(), nullable=False),
    sa.Column('safe_max_temp_c', sa.Float(), nullable=False),
    sa.Column('initial_shelf_life_hours', sa.Float(), nullable=False),
    sa.Column('truck_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=32), nullable=False),
    sa.Column('location_kind', sa.String(length=16), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('product_batches')
    op.drop_table('devices')
    op.drop_table('warehouses')
    op.drop_table('trucks')
    op.drop_table('stores')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_sensor_readings_ts'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_truck_id'), table_name='sensor_readings')
    op.drop_index('ix_readings_truck_ts', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('routes')
    op.drop_table('rejected_readings')
    op.drop_table('products')
    op.drop_index(op.f('ix_incidents_truck_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
